version: '3.8'

services:
  backend:
    build:
      context: ./Fitness_Tracker_Backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
    restart: always

  frontend:
    build:
      context: ./Fitness_Tracker_Frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=http://localhost:5000/api
    ports:
      - "80:80"
    restart: always
    depends_on:
      - backend
